[package]
name = "orderbook"
version = "0.1.0"
edition = "2021"

[lib]
name = "orderbook_lib"
path = "src/lib.rs"

[[bin]]
name = "orderbook-bin"
path = "src/main.rs"

[profile.release]
opt-level=3
lto = true
debug = 1
# codegen-units=1
# strip = 'symbols' Figure out later

[profile.bench]
debug = true

[dependencies]
rand = "0.8.4"
serde = { version = "1.0", features = ["derive"]}
csv = "1.3.0"
pretty_assertions = "1.4"
rstest = "0.19"

[dev-dependencies]
criterion = {version = "0.5.1", features = ["html_reports"]}
# tempfile = "3.10"

[[bench]]
name = "order_benchmark"
harness = false

