[package]
name = "orderbook"
version = "0.1.0"
edition = "2021"
[lib]
name = "orderbook"
path = "src/lib.rs"

[[bin]]
name = "orderbook-bin"
path = "src/main.rs"

[profile.release]
opt-level='z'
lto = true
codegen-units=1
strip = 'symbols'

[profile.bench]
debug = true

[dependencies]
rand = "0.8.4"

[dev-dependencies]
criterion = "0.5.1"
pretty_assertions = "1.4"
tempfile = "3.10"

[[bench]]
name = "order_benchmark"
harness = false
